/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Oct 16 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include "timer.h"
#include <stm32f103x6.h>
#include <stdint.h>
#include "delay.h"
#include "lcd.h"
#include "spi.h"


int main (void)
 { 
    timer_init();
    spi1_init();
    lcd_init();
    activeSpi();
    while(1){
       if (timer_getFlag()){
	      leerTemp();
	      imprimirTemp();
	      timer_resetFlag();
	 }

     }
 }   



